replicaCount: 1
image:
  repository: "1983vi/icom-catalog-service"
  tag: "v1.1.0"
  pullPolicy: Always
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
resources: {}