server.port: 7001
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring:
#  profiles.active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

app:
  prod: false
  defaultPageSize: 10
  inventory-service:
    host: http://INVENTORY-SERVICE/inventory


security:
  oauth2:
    client:
      clientId: catalog-service
      clientSecret: CATALOG_SERVICE_PASSWORD
      accessTokenUri: http://${app.oauth2-host}:5000/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://${app.oauth2-host}:5000/users/current
spring.main.allow-bean-definition-overriding: true

spring.cloud.stream:
  bindings:
    output-audit:
      destination: audit-support
      producer:
        required-groups: auditGroup

feign.hystrix.enabled: true
hystrix.metrics.enabled: true