server.port: 7009
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring:
#  profiles.active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

app:
  prod: false
  defaultPageSize: 10

security:
  oauth2:
    client:
      clientId: orchestrator-service
      clientSecret: ORCHESTRATOR_SERVICE_PASSWORD
      accessTokenUri: http://${app.oauth2-host}:5000/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://${app.oauth2-host}:5000/users/current
spring.main.allow-bean-definition-overriding: true

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.order-input:
    destination: order-topic

feign:
  client:
    url:
      inventoryService: http://inventory-service
      paymentService: http://payment-service
feign.hystrix.enabled: true
hystrix.metrics.enabled: true              
        
        