server.port: 7002

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring.application.name: inventory-service

app:
  message: hello inventory service
  prod: false
  defaultPageSize: 10
  eureka-server: localhost
  oauth2-host: localhost
    
security:
  oauth2:
    client:
      clientId: inventory-service
      clientSecret: INVENTORY_SERVICE_PASSWORD
      accessTokenUri: http://${app.oauth2-host}:5000/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://${app.oauth2-host}:5000/users/current


spring:
#  profiles.active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: false
      path: /h2-console

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

        
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

---
spring.profiles: docker

spring.rabbitmq.host: rabbitmq

app.eureka-server: service-discovery