server.port: 8080

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring.application.name: inventory-service

app:
  message: Hello 
  prod: false
  defaultPageSize: 10
  #eureka-server: localhost
  oauth2-host: http://auth-server
  #oauth2-host: https://bycnitsite.westeurope.cloudapp.azure.com/oauth
    

spring:
  profiles.active: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate.format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
      path: /h2-console

#host:
  #auth-server: https://bycnitsite.westeurope.cloudapp.azure.com/oauth

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${app.oauth2-host}/oauth/check_token
          client-id: inventory-service
          client-secret: INVENTORY_SERVICE_PASSWORD

spring.zipkin.baseUrl: http://40.68.201.25:9411
logging.file.name : ./log/inventory-service.log
logging.level.org.springframework.web.servlet.DispatcherServlet: TRACE

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

        
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://${app.eureka-server}:8761/eureka/
#     initialInstanceInfoReplicationIntervalSeconds: 5
#     registryFetchIntervalSeconds: 5
#   instance:
#     leaseRenewalIntervalInSeconds: 5
#     leaseExpirationDurationInSeconds: 5
# 
# ribbon.ServerListRefreshInterval: 5000
# 
# ribbon.NFLoadBalancerPingInterval: 5

---
# spring.profiles: docker
# 
# spring.rabbitmq.host: rabbitmq
# 
# app.eureka-server: service-discovery