#server.port: 7002

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring.application.name: inventory-service

app:
  message: hello inventory service
  prod: false
  defaultPageSize: 10
  #eureka-server: localhost
  oauth2-host: http://auth-server
    
security:
  oauth2:
    client:
      clientId: inventory-service
      clientSecret: INVENTORY_SERVICE_PASSWORD
      accessTokenUri: ${app.oauth2-host}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: ${app.oauth2-host}/users/current


spring:
#  profiles.active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: false
      path: /h2-console

spring.zipkin.baseUrl: http://40.68.201.25:9411
logging.file.name : ./log/inventory-service.log
logging.level.org.springframework.web.servlet.DispatcherServlet: TRACE

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

        
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://${app.eureka-server}:8761/eureka/
#     initialInstanceInfoReplicationIntervalSeconds: 5
#     registryFetchIntervalSeconds: 5
#   instance:
#     leaseRenewalIntervalInSeconds: 5
#     leaseExpirationDurationInSeconds: 5
# 
# ribbon.ServerListRefreshInterval: 5000
# 
# ribbon.NFLoadBalancerPingInterval: 5

---
# spring.profiles: docker
# 
# spring.rabbitmq.host: rabbitmq
# 
# app.eureka-server: service-discovery