app:
  eureka-server: localhost
    
spring:
  application.name: auth-service
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: true
      path: /h2-console
    
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://${app.eureka-server}:8761/eureka/
#     initialInstanceInfoReplicationIntervalSeconds: 5
#     registryFetchIntervalSeconds: 5
#   instance:
#     leaseRenewalIntervalInSeconds: 5
#     leaseExpirationDurationInSeconds: 5
# ribbon.ServerListRefreshInterval: 5000
# ribbon.NFLoadBalancerPingInterval: 5

# spring.cloud.stream:
#   defaultBinder: rabbit
#   default.contentType: application/json
# 
# spring.rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
          
---
# spring.profiles: docker
# 
# spring.rabbitmq.host: rabbitmq
# 
# app.eureka-server: service-discovery

