apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{.Release.Name}}
  namespace: kube-public
spec:
  secretName: {{.Values.secretName}}
  dnsNames:
    - {{.Values.fqdn}}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - {{.Values.fqdn}}
  issuerRef:
    name: {{.Values.letsencryptName}}
    kind: ClusterIssuer
