apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}
  namespace: kube-public
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{.Values.issuer}}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{.Values.fqdn}}
      secretName: {{.Values.tlssecretname}}
  rules:
    - host: {{.Values.fqdn}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.servicename}}
              servicePort: 80
          - path: /oauth/(.*)
            backend:
              serviceName: auth-server
              servicePort: 80


