server.port: 7003
spring.application.name: audit-service
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring:
#  profiles.active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    generate-ddl: false
    open-in-view: false         
    hibernate:                 
      ddl-auto: create  
  h2:
    console:
      enabled: false
      path: /h2-console
  cloud:
    function:
      definition: catalogAudit  
    stream:
      default.contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        catalogAudit-in-0:
            content-type: application/json
            destination : catalog-audit-topic 
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug

app:
  prod: false
  defaultPageSize: 10
  eureka-server: localhost
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5



        
#spring.zipkin.baseUrl: http://zipkin-server:9411
logging.file.name : ./log/audit-service.log
logging.level.org.springframework.web.servlet.DispatcherServlet: TRACE

---
# spring.profiles: docker
# 
# spring.rabbitmq.host: rabbitmq
# 
# app.eureka-server: service-discovery
  